bee:
  data:
    redis:
      test_single:
        type: single
        address:
          - 101.201.235.73:8379
        master: m1
        password: '123456'
        max_pool_size: 100
        socket_connect_timeout: 5000
        socket_timeout: 5000
      test_cluster:
        type: cluster
        address:
          - 127.0.0.1:7001
          - 127.0.0.1:7002
          - 127.0.0.1:7003
          - 127.0.0.1:7004
          - 127.0.0.1:7005
          - 127.0.0.1:7006
        master: m1
        password: ''
        max_pool_size: 100
        socket_connect_timeout: 5000
        socket_timeout: 5000